apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mdmkgt07l-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/mdmkgt07l-java-springboot-gitops